### PR TITLE
Add support for multiple allowable entry types, allow `Effect`

### PR DESCRIPTION
**Pull request by garyb**
Also fixed it so the tests work again :wink: maybe could set up Travis on this repo?

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
Relates to https://github.com/purescript-contrib/pulp/issues/337

**Comment by garyb** [comment]
I was thinking maybe we could make a patch-version release of pulp with this in (since Effect is usable in 0.11.x too), and then do another update that changes the project scaffolding, etc. to use Effect by default, perhaps.

**Comment by LiamGoodacre** [comment]
:+1: Yeah that makes sense

**Comment by hdgarrood** [comment]
Sounds good to me. This looks good :+1:, although I think I'd prefer to keep the use of `V` as an implementation detail, so that we would not export `checkEntryPointV` and we'd modify the tests so that they can deal with getting the result back as an `Either` instead of a `V`. I should indeed set up CI as well.

If you'd like I can merge this, do the above, and then release a new version of this library?

**Comment by garyb** [comment]
Thanks! I wasn't sure whether hiding the V was intentional or not, I thought it might have been a mistaken missing import.

**Pull request merged**
